In [3]:
import numpy as np

In [6]:
a1=np.array([1,2,3])#1d

In [10]:
a2=np.array([[1,2,3],[4,5,6]])#2d

In [11]:
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])#3d

In [12]:
a1

array([1, 2, 3])

In [13]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])